---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

The information below is a summary of Helen's academic and professional experiences. 

**EDUCATION**
MS Environmental Health Data Science, 2025 
Columbia University Mailman School of Public Health 						            
Thesis: Nutrition and Stress as Effect Modifiers During Pre-Natal Air Pollution Exposure on Childhood Lung Function in GRAPHS cohort 
Thesis advisor: Dr. Darby Jack 	

BS Medicinal Biochemistry, Honors, 2024 
William Paterson University 
Public Health minor (summa cum laude)
Thesis: Closed Captioning: Culturally Competent and Linguistically Concordant Healthcare (Global Public Health Honors Research Track)
Thesis advisor: Dr. Marianne Sullivan					   		   

**PUBLICATIONS**
Basch, C.H., Yousaf, H., Fera, J.et al.YouTube as a Source of Information on Air Pollution: Significance for Community Health.J Community Health (2024). https://doi.org/10.1007/s10900-024-01360-7
Yousaf, H., Fera, J., & Basch, C. H. (2024). Coverage of Air Pollution in Online News: Implications for Environmental Health Awareness. Journal of Consumer Health on the Internet, 1–9. https://doi.org/10.1080/15398285.2024.2385221
Basch CH, Yousaf H, Fera J, Gonzalez R. Traffic as an Urban Health Determinant: Coverage of the New York City Congestion Pricing Plan on TikTok. In press.
Basch CH, Kollia B, Park E, Yousaf H. Investigation of the online news content provided to the public regarding noise pollution. Noise and Health. Under Review.
Basch CH, Hillyer GC, Yousaf H, Basch CE. The Zyn Wave: Analyzing the Popularity of #zyn content on TikTok. Under Review. 
Basch CH, Kollia B, Park E, Yousaf H. Noise pollution: impact on communication, mental, and physical health in YouTube videos.Under Review.

**CONFERENCES**
Helen Yousaf, David A Snyder, Biophysical Chemistry of Aging, Undergraduate Research Symposium, William Paterson University, April 2024
H. Yousaf, Between the Diagnosis: The Importance of Linguistic and Cultural Competency in Healthcare, National Collegiate Honors Council Annual Conference, Chicago, IL, November 2023
H. Yousaf, Between the Diagnosis: The Importance of Linguistic and Cultural Competency in Healthcare, National Society for Minorities in Honors Conference, University of Arkansas, October 2023 (Accepted; unable to attend)
H. Yousaf, S. Gritsch, J. Foley, Future Pioneer Project – An Integrated Program to Expand Knowledge of Sustainable Energy Technologies: Year I: Passive Radiative Cooling, Nano-chemistrycategory, Undergraduate Research Symposium, William Paterson University, March 2022


**RESEARCH EXPERIENCE**
Practicum Research Assistant, 2024 - Present
Collaborative Lab for Energy Access Research and Solutions (CLEARS); Advisor: Dr. Darby Jack 
Department of Environmental Health Sciences 
Mailman School of Public Health, Columbia University 
Development of data infrastructure/system from GRAPHS (The Ghana Randomized Air Pollution and Health Study) cohort assessing role of nutrition as an effect modifier for air pollution effects 
Collaborate with post-doctoral research follow to determine whether stress and air pollution exposure have symbiotic impacts on health outcomes 
Collaborating with investigator from Mount Sinai Hospital to develop database, analyze nutritional biomarkers, and formalize into written thesis for Maters of Science degree requirements 

Research Assistant, 2024-Present
Kupsco Lab on Environmental Epigenetics and Children’s Health; PI: Dr. Allison Kupsco
Department of Environmental Health Sciences 
Mailman School of Public Health, Columbia University 
Statistical analysis of effect of PROGRESS metals birth cohort on childhood and adolescent sleep patterns 
Using teeth and blood metal levels as biomarkers of exposure to determine whether prenatal, antenatal, and early childhood exposure to metals impacts sleep behavior and cycles of children 
Working with an interdisciplinary team of metabolic and epigenetic researchers to characterize metal-neurodevelopmental and cognitive interactions of a longitudinal, cohort-based study 
Participate in weekly seminar presentations learning about quantitative methods for manipulation of metabolic and molecular data related to environmental epigenetics and genomics 
Development of a data analysis plan 

Graduate Research Assistant, 2024-Present
Developing a Research and Rights Agenda to Address the Needs and Foster the Capabilities of Displaced Older Adults
International Longevity Center and Robert N. Butler Columbia Aging Center; PI: Dr. John Beard, Co-PI: Dr. Maureen Henry
Department of Health Policy and Management, Presidential Global Innovation Fund
Mailman School of Public Health, Columbia University 
Student lead on scoping umbrella review on the impact of conflict, natural disasters, and climate change forcing older populations to migrate using a humanitarian relief framework  
Author briefing paper assessing the impact of age and refugee status on eight health-related domains: to share with experts in Global Forum in Amman, Jordan 
Travel to Amman, Jordan in February 2025 to meet with global experts on ageing and elderly IDPs including officials from the United Nations, USAID, HelpAge, and Norweigen Embassy 
Coordinate with Columbia Global Center - Amman in Jordan to determine logistics of holding conference in February 2025 and establish list of global experts to attend conference including philanthropists, journalists, and political figures  
Prepare and distribute Delphi study for local and global meeting in Amman, Jordan and analyze results
Draft literature review paper detailing the impact of forced migration and displacement on older persons in Jordan 
Simultaneously work with Robert N. Butler Columbia Aging Center on related research study performing Triad interviews on the self-perceptions, perceived perceptions, and concerns of aging populations in Washington Heights, New York

Research Assistant, 2023- Present
William Paterson University 
Department of Public Health; PI: Dr. Corey Basch
Collaborating in a mixed-methods research group analyzing the social, structural, and environmental determinants of urban, community, and global health outcomes; more specifically related to air pollution, noise pollution, social media and health communication, legislative policy, substance abuse 
Research methodology primarily focused on the long-lasting health impacts of denizens interacting with their social, built, and natural environments and the role of health communication and individual behavior development 
Led data collection on 10 unique research studies using survey and qualitative research methods including sampling, inductive and deductive reasoning, and data coding
Developed 2 IRB approved Knowledge, Attitude, and Behavior survey instruments to measure behaviors of college-aged students related to global climate change and artificial intelligence 
Work led to successful completion of 1 first-authored and 8 co-authored peer-reviewed manuscripts for publications 

Undergraduate Research Assistant, 2022 - 2024
National Science Foundation Grant
Collaborative research, William Paterson University and Columbia University
Socio-economic patterns, public perceptions, and climate vulnerabilities of water resources and quality in the NY-NJ Watershed 
Departments of Public Health, Environmental Science, and Community and Social Justice Studies; PI: Dr. Lilian Milanés	
Performed systematic literature reviews and analyzed data on water perception and access in minority and disadvantaged communities in the Sri-state region to assess further need for quality and health testing 
Partnered with Passaic County and State of New Jersey stakeholders, Jersey Water Works, to meet demand for careers and workforce training in water-jobs  
Drafted Internal Review Board application for focus group approval and converted participant survey results into data record file
Developed and planned community-service projects on campus in collaboration with Center for Diversity and Inclusion to increase awareness about water-insecurity 

Special Project Undergraduate Research Assistant, 2022
William Paterson University 
Department of Public Health; Mentor: Dr. Corey Basch
Surveyed the New York State Hospital system to assess access to preventative and follow-up care for diabetic patients in the NY Metropolitan area based on health insurance type and coverage
Contacted ophthalmologists, cardiologists, and endocrinologists to collect data on average phone wait times and appointment availability for new patients with various insurance coverages and health conditions

**TEACHING EXPERIENCE**
Honors Peer Leader, 2022 - 2024
Honors College, William Paterson University 
Facilitated HON1020 introductory courses for Honors first-year and transfer students
Held weekly Office Hours to answer student questions and offer additional guidance
Organized and hosted yearly Honors events to increase civic engagement and student participation, including Annual Coat Drive, Honors Week and Reception, and Orientation
Co-organized civic engagement project, Slices of Service, and workshop panel to encourage student participation in community engagement and reflection on the direct and in-direct impacts of service projects
Assisted Dean and Associate Director with administrative tasks related to student enrollment, marketing, and other tasks as assigned

Tutor, 2018-2021
Worked one-on-one with students, grades 5-11, to develop and improve study habits and achieve academic success by creating study guides, practice quizzes, and study materials.
Aided with homework questions and confusion on course material with specific experience in STEM, social science, and foreign language courses for elementary through high school students

**PROFESSIONAL AND LEADERSHIP EXPERIENCE**
Graduate Administrative Assistant, 2024-Present
Digital Learning Studio, Mailman School of Public Health, Columbia University Irving Medical Center 
Read and completed more than 200 peer-reviewed journal articles, book chapters, and technical papers that led to the successful development of RISE Reading Summary Learning Modules for 9 graduate-level courses that will be implemented in Spring 2025 semester: PUBHP6053: Public Health Interventions, PUBHP6054: Global and Development Perspectives, PUBHP6062: Health Systems, PUBH 6073: Integration of Science and Practice II, P6082: Personal Leadership, P6766: Designing Needs and Assets Assessment, P8095: Communicating Health Risks, P8304: The Impact of Climate Change on Public Health, and P8620: Implementation Science in Practice, P8096: Communicating Health Risks to the Public, P8304: The Impact of Climate Change on Public Health 
Develop RISE Learning Modules for online-instruction students in Mailman Accelerated MPH program for Spring 2025 course: P8620: Implementation Science in Practice
Write reading summaries based on instructor lesson plans
Design asynchronous learning content using Mailman MPH core curriculum materials 

Office Intern, 2023- 2024
Honors College, William Paterson University 
Won regional and national competitions as author and editor of monthly newsletter
Aggregated University news to share upcoming deadlines, events, and reminders with students 
Collaborated with Honors Faculty and staff on program planning goals and initiatives 

Student Assistant, 2022- 2023
Counseling, Health, and Wellness Center, William Paterson University
Led administrative support to WP and FastMed LLC on-site COVID-19 testing and vaccine clinics in safe return-to campus initiative post-lockdowns 
Collaborated with licensed counselors to input data for the Columbia University Suicide Screening Survey
Managed medication supply and packaging under supervision of Charge Nurse and more than 1500 COVID-19 antigen tests for resident students
Obtained pertinent history related to mental health and primary care at the time of appointments and triage

Student Assistantship, 2021-2022
Department of Chemistry, William Paterson University
Successful presentation of clean energy heating/cooling techniques at annual undergraduate research symposium in nano chemistry category 
Promoted the Future Pioneer Project, a project funded by a National Science Foundation grant focusing on sustainable development of cooling and heating techniques to address carbon-expensive household appliances 
Organized yearly Future Pioneer Fest and “unconference”.
Assessed diversity and effectiveness of project through participant surveys and collaboration with Center for Diversity and Inclusion

**LANGUAGES**
Fluent: Dari, English, Farsi, French, German, Hindi, Urdu and Proficient: Italian, Spanish, and Turkish 

**SKILLS**
R, SPSS, GIS, Stata

**CERTIFICATIONS**
CITI Health Research Certification, Columbia-Suicide Severest Rating Scale Training, HIPAA for Mental Health, Heart Savers CPR